Repository team-easymap/easymap-frontend, pull requests merged in 2024-08, with the labels that each got.

#22 Feat/21
  src/assets/AppleIcon.svg
  src/assets/Character.svg
  src/assets/GoogleIcon.png
  src/assets/KaKaoIcon.svg
  src/pages/login.tsx
  src/router/index.tsx
  tailwind.config.js
Labels: 🎨 Html&css

#28 feat: 공통컴포넌트 구현
  package.json
  src/assets/icons/check.svg
  src/components/ui/checkbox.tsx
  src/components/ui/chip.tsx
  src/components/ui/icon.tsx
  src/components/ui/radio-group.tsx
  src/globals.css
  tailwind.config.js
  yarn.lock
Labels: 🎨 Html&css

#31 feat: 프리티어 적용
  .gitignore
  .vscode/settings.json
  src/components/common/footerButton.tsx
  src/globals.css
Labels: ✨ Feature

#34 feat: 최근 검색어 마크업
  index.html
  src/components/search/search-form/search.tsx
  src/components/search/search-history/search-history-list.tsx
  src/components/search/search-history/search-history.tsx
  src/components/ui/button.tsx
  src/components/ui/icon.tsx
  src/globals.css
  src/leaflet.css
Labels: ✨ Feature

#35 feat: 검색 구현
  src/components/search/search-form/search-clear-button.tsx
  src/components/search/search-form/search-form.tsx
  src/components/search/search-form/search.tsx
  src/hooks/common/useDebounce.ts
  yarn.lock
Labels: ✨ Feature

#36 Feat/15
  src/assets/smile.svg
  src/components/common/Header.tsx
  src/components/signup/ProfileDetailsForm.tsx
  src/components/signup/TermsForm.tsx
  src/components/signup/TermsModal.tsx
  src/components/signup/UserInfoForm.tsx
  src/pages/signup.tsx
  src/router/index.tsx
Labels: 🎨 Html&css

#38 feat: 장소 상세 페이지 마크업
  src/App.tsx
  src/assets/icons/star-fill.svg
  src/assets/profile.svg
  src/components/layout/footer.tsx
  src/components/layout/layout.tsx
  src/components/main/search.tsx
  src/components/poi/poi-ally.tsx
  src/components/poi/poi-buttons.tsx
  src/components/poi/poi-description.tsx
  src/components/poi/poi-images.tsx
  src/components/poi/poi-reviews.tsx
  src/components/poi/review/review-images.tsx
  src/components/poi/review/review-info.tsx
  src/components/poi/review/review.tsx
  src/components/search/search-routes/search-routes.tsx
  src/components/ui/chip.tsx
  src/components/ui/icon.tsx
  src/lib/utils.ts
  src/pages/poi.tsx
  src/pages/search.tsx
  src/router/index.tsx
Labels: ✨ Feature

#39 Feat/25
  package-lock.json
  src/components/main/header.tsx
  src/components/main/icon.tsx
  src/components/main/search.tsx
  src/components/main/tag.tsx
  src/leaflet.css
  src/pages/main.tsx
  tsconfig.app.json
  tsconfig.node.json
  yarn.lock
Labels: 🎨 Html&css, ✨ Feature

#42 refactor: 현 위치 기능 코드 수정
  src/components/layout/layout.tsx
  src/components/main/location.tsx
  src/components/main/map.tsx
  src/components/main/myMarker.tsx
  src/pages/main.tsx
Labels: 🔨 Refactor

#45 feat: 검색 수정
  package-lock.json
  src/assets/warning-lg.svg
  src/components/common/empty-list.tsx
  src/components/layout/layout.tsx
  src/components/search/search-form/search-clear-button.tsx
  src/components/search/search-form/search-form.tsx
  src/components/search/search-form/search.tsx
  src/components/search/search-result/result-empty.tsx
  src/components/search/search-result/result-list.tsx
  src/components/search/search-routes/search-routes.tsx
  src/mocks/search-result.ts
  src/pages/search.tsx
  src/types/pois.ts
  yarn.lock
Labels: ✨ Feature

#47 feat: 장소 목록 마크업 구현
  package.json
  src/components/common/rating.tsx
  src/components/layout/layout.tsx
  src/components/poi-list/category.tsx
  src/components/poi-list/poi-list.tsx
  src/components/ui/chip.tsx
  src/components/ui/icon.tsx
  src/lib/utils.ts
  src/pages/poi-list.tsx
  src/router/index.tsx
  tailwind.config.js
  yarn.lock
Labels: ✨ Feature

#51 Feat/48
  src/components/main/search.tsx
  src/components/search/search-form/search-form.tsx
  src/components/search/search-form/search.tsx
  src/components/search/search-history/search-history-list.tsx
  src/components/search/search-history/search-history.tsx
  src/components/search/search-result/result-list.tsx
  src/components/search/search-routes/rotate-button.tsx
  src/components/search/search-routes/search-routes-form.tsx
  src/components/search/search-routes/search-routes.tsx
  src/pages/poi.tsx
  src/pages/search.tsx
Labels: ✨ Feature

#53 feat:장소 수정 컴포넌트 추가
  package.json
  src/components/common/commonButton.tsx
  src/components/poi/modify/daumAddressInput.tsx
  src/components/poi/modify/imageInput.tsx
  src/components/poi/modify/modify-address.tsx
  src/components/poi/modify/modify-box.tsx
  src/components/poi/modify/modify-category.tsx
  src/components/poi/modify/modify-tag.tsx
  src/components/poi/modify/modify.tsx
  src/components/ui/dialog.tsx
  src/pages/poi-modify.tsx
  src/router/index.tsx
  yarn.lock
Labels: ✨ Feature

#54 feat: 경로 검색 수정
  src/components/search-routes/form/rotate-button.tsx
  src/components/search-routes/form/search-routes-form.tsx
  src/components/search-routes/form/search-routes.tsx
  src/components/search-routes/result/routes-result-map.tsx
  src/components/search-routes/result/routes-result.tsx
  src/components/search/search-history/search-history.tsx
  src/components/search/search-result/result-list.tsx
  src/components/search/search-routes/search-routes.tsx
  src/mocks/search-result.ts
  src/pages/search-routes.tsx
  src/pages/search.tsx
  src/router/index.tsx
Labels: ✨ Feature

#55 refactor:장소 수정 이미지 관련 수정, 이미지 공통 컴포넌트 추가
  src/components/common/commonImage.tsx
  src/components/poi/modify/imageInput.tsx
  src/pages/poi-modify.tsx
Labels: 🔨 Refactor

#57 feat: 리뷰 등록, 수정 구현 및 이미지, 주소 공통컴포넌트 등록
  src/components/common/daumAddressInput.tsx
  src/components/common/imageInput.tsx
  src/components/poi/modify/poi-modify-address.tsx
  src/components/poi/modify/poi-modify-box.tsx
  src/components/poi/modify/poi-modify-category.tsx
  src/components/poi/modify/poi-modify-tag.tsx
  src/components/poi/modify/poi-modify.tsx
  src/components/poi/review/modify/rating-make.tsx
  src/components/poi/review/modify/review-content.tsx
  src/components/poi/review/modify/review-modify-box.tsx
  src/components/poi/review/modify/review-modify.tsx
  src/components/poi/review/modify/saveButton.tsx
  src/components/ui/textarea.tsx
  src/pages/poi-modify.tsx
  src/pages/poi-review-modify.tsx
  src/router/index.tsx
Labels: 🔨 Refactor, ✨ Feature

#58 feat: 경로 검색 결과 마크업, 최근 검색어 저장 수정
  src/assets/icons/search.svg
  src/components/search-routes/result/routes-result-list.tsx
  src/components/search-routes/result/routes-result.tsx
  src/components/search/search-history/search-history-list.tsx
  src/components/search/search-history/search-history.tsx
  src/components/search/search-result/result-list.tsx
  src/components/ui/icon.tsx
  src/globals.css
  src/hooks/common/useLocalStorage.ts
  src/lib/utils.ts
  src/mocks/search-result.ts
  src/pages/search-routes.tsx
  src/pages/search.tsx
Labels: ✨ Feature

#60 feat: 장소 검색 결과 마크업
  src/components/common/rating.tsx
  src/components/poi-list/poi-list.tsx
  src/components/search-poi-result/poi/poi-buttons.tsx
  src/components/search-poi-result/poi/poi-images.tsx
  src/components/search-poi-result/poi/poi-info.tsx
  src/components/search-poi-result/poi/poi-tags.tsx
  src/components/search-poi-result/poi/search-poi-result.tsx
  src/components/search-poi-result/result-header.tsx
  src/components/search-poi-result/result-map.tsx
  src/components/search/search-result/result-list.tsx
  src/mocks/poi.ts
  src/pages/search-poi-result.tsx
  src/router/index.tsx
  src/types/pois.ts
Labels: ✨ Feature

#63 feat: 경로 기록 버튼 추가
  src/components/main/header.tsx
  src/components/main/map.tsx
  src/components/main/record.tsx
  yarn.lock
Labels: ✨ Feature

#65 Feat/16
  src/components/layout/layout.tsx
  src/components/mypage/Modal.tsx
  src/components/signup/ProfileDetailsForm.tsx
  src/components/signup/profileDetailsForm/NickNameInput.tsx
  src/components/signup/profileDetailsForm/ProfileDetailsForm.tsx
  src/components/signup/profileDetailsForm/ProgileImgEdit.tsx
  src/pages/mypage.tsx
  src/router/index.tsx
Labels: 🎨 Html&css, 🔨 Refactor, ✨ Feature

#68 Feat/67
  src/components/signup/UserInfoForm.tsx
  src/components/signup/profileDetailsForm/ProgileImgEdit.tsx
  src/pages/profileEdit.tsx
  src/router/index.tsx
Labels: 🎨 Html&css, ✨ Feature

#70 feat: 최근 검색 경로 수정
  src/assets/search-lg.svg
  src/components/search-routes/history/routes-history.tsx
  src/components/search-routes/result/routes-result.tsx
  src/components/search/search-history/history-empty.tsx
  src/hooks/common/useLocalStorage.ts
  src/pages/search-routes.tsx
Labels: ✨ Feature

#72 feat: 최근 장소 검색 선택 수정
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  src/components/search/search-history/search-history-list.tsx
  src/components/search/search-history/search-history.tsx
  src/pages/search.tsx
  yarn.lock
Labels: ✨ Feature

#74 feat: 컨펌 컴포넌트 추가
  package.json
  src/components/common/confirm.tsx
  src/components/ui/alert-dialog.tsx
  yarn.lock
Labels: ✨ Feature

#76 feat: 경로 검색 결과 페이지 구현
  src/components/main/map.tsx
  src/components/search-routes-result/map.tsx
  src/components/search-routes/result/routes-result-list.tsx
  src/pages/search-routes-result.tsx
  src/pages/search-routes.tsx
  src/router/index.tsx
  src/types/pois.ts
Labels: ✨ Feature

#79 feat: 등록되지 않은 장소 선택 결과 구현
  src/components/common/rating.tsx
  src/components/main/poiMarker.tsx
  src/components/search-poi-result/poi/poi-buttons.tsx
  src/components/search-poi-result/poi/poi-images.tsx
  src/components/search-poi-result/poi/poi-info.tsx
  src/components/search-poi-result/poi/search-poi-result.tsx
  src/components/search-poi-result/result-map.tsx
  src/components/search-routes/history/routes-history.tsx
  src/components/search/search-history/search-history-list.tsx
  src/components/search/search-history/search-history.tsx
  src/components/search/search-result/result-list.tsx
  src/mocks/search-result.ts
  src/pages/search-poi-result.tsx
  src/pages/search.tsx
  src/types/pois.ts
Labels: ✨ Feature

#82 feat: 장소 페이지 버튼 수정, 푸터 버튼 수정
  src/components/layout/footer.tsx
  src/components/poi/poi-ally.tsx
  src/components/poi/poi-buttons.tsx
  src/components/poi/poi-description.tsx
  src/components/poi/poi-images.tsx
  src/components/search-poi-result/poi/poi-buttons.tsx
  src/components/search-poi-result/poi/poi-images.tsx
  src/components/search-poi-result/poi/poi-info.tsx
  src/components/search-poi-result/poi/poi-tags.tsx
  src/components/search-poi-result/poi/search-poi-result.tsx
  src/components/search-poi-result/search-poi-result.tsx
  src/hooks/common/useClipboard.ts
  src/pages/poi.tsx
  src/pages/search-poi-result.tsx
Labels: ✨ Feature

#84 view 기준 좌표 구하기, 현 위치 재검색 기능
  src/components/main/view-corner.tsx
Labels: ✨ Feature

#88 feat: 장소 목록 메인으로 이동
  src/components/common/footerButton.tsx
  src/components/layout/footer.tsx
  src/components/layout/layout.tsx
  src/pages/main.tsx
  src/router/index.tsx
Labels: ✨ Feature

#89 poi 등록, 수정 리팩토링
  src/components/common/imageInput.tsx
  src/components/layout/footer.tsx
  src/components/poi/modify/poi-modify.tsx
  src/components/poi/register/poi-register.tsx
  src/components/poi/ui/poi-address.tsx
  src/components/poi/ui/poi-box.tsx
  src/components/poi/ui/poi-category.tsx
  src/components/poi/ui/poi-modify-box.tsx
  src/components/poi/ui/poi-tag.tsx
  src/router/index.tsx
Labels: 🔨 Refactor

#92 feat: 장소 목록 바텀시트 컴포넌트 구현
  package.json
  src/components/layout/footer.tsx
  src/components/layout/layout.tsx
  src/components/main/poi-list/poi-item.tsx
  src/components/main/poi-list/poi-list-tab.tsx
  src/components/main/poi-list/poi-list.tsx
  src/components/poi-list/poi-list.tsx
  src/hooks/common/useBottomSheet.tsx
  src/main.tsx
  src/pages/main.tsx
  src/pages/poi-list.tsx
  yarn.lock
Labels: ✨ Feature

#94 Feat/93
  src/components/main/poi-list/poi-item.tsx
  src/components/main/poi-list/poi-list-tab.tsx
  src/components/main/poi-list/poi-list.tsx
  src/const/category.ts
  src/hooks/common/useBottomSheet.tsx
Labels: ✨ Feature

#99 feat: 검색페이지 스타일 수정
  src/components/layout/layout.tsx
  src/components/main/poi-list/poi-list-tab.tsx
  src/components/main/poi-list/poi-list.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/globals.css
  src/pages/poi.tsx
  yarn.lock
Labels: 🎨 Html&css

#101 feat: poi 등록, 수정 api
  package.json
  src/components/main/map.tsx
  src/components/main/poi-save.tsx
  src/queries/add-poi.ts
  src/queries/get-poi.ts
  src/store/poi.ts
  yarn.lock
Labels: ✨ Feature

#102 feat: 카테고리 api
  src/queries/get-categories.ts
  src/queries/get-poi.ts
Labels: ✨ Feature

#105 feat: 좌표 기반 주소 받기
  src/queries/get-address.ts
Labels: ✨ Feature

#110 feat: 지도 장소 선택 수정
  src/components/common/select-location.tsx
  src/components/main/map.tsx
  src/components/poi/poi-buttons.tsx
  src/components/search-poi-result/result-map.tsx
  src/components/search-routes-result/map.tsx
  src/hooks/useSelectMap.tsx
  src/pages/main.tsx
  src/pages/search-poi-result.tsx
  src/pages/search-routes-result.tsx
Labels: ✨ Feature

#114 feat: axios instance 추가
  package.json
  src/api/axiosInstance.ts
  vite.config.ts
  yarn.lock
Labels: ✨ Feature

#115 feat: 자동완성 검색 구현
  src/api/search.ts
  src/hooks/queries/useSearchList.ts
  src/main.tsx
  src/pages/search.tsx
Labels: ✨ Feature

#116 feat: 자동완성검색 요청 수정
  package.json
  src/api/axiosInstance.ts
  src/api/search.ts
  src/api/signIn.ts
  src/components/search/search-result/result-list.tsx
  src/hooks/queries/useSearchList.ts
  src/main.tsx
  src/pages/login.tsx
  src/pages/search.tsx
  vite.config.ts
  yarn.lock
Labels: ✨ Feature

#118 feat: 인스턴트 poi 생성 요청
  src/api/poi.ts
  src/hooks/queries/useInstantPOI.ts
Labels: ✨ Feature

#119 feat: 주소 기반 좌표 받기
  src/api/search.ts
  src/components/search/search-result/result-list.tsx
  src/hooks/queries/useCoords.ts
Labels: ✨ Feature

#121 Feat/106
  package.json
  src/components/main/map.tsx
  src/components/main/view-corner.tsx
  src/components/main/view-move.tsx
  src/queries/get-view-poi.ts
  src/store/location.ts
  src/store/poi.ts
Labels: ✨ Feature

#122 feat: 인스턴트 POI 생성 요청
  src/api/search.ts
  src/api/signIn.ts
  src/components/search/search-result/result-list.tsx
  src/hooks/queries/useInstantPOI.ts
  src/pages/search-routes.tsx
Labels: ✨ Feature

#124 Feat/78
  src/components/common/Modal.tsx
  src/components/common/rating.tsx
  src/components/my-reviews/imgItem.tsx
  src/pages/myReviews.tsx
  src/pages/mypage.tsx
  src/router/index.tsx
Labels: ✨ Feature

#125 poi 관련 api 요청 수정 - 카테고리
  .gitignore
  package.json
  src/api/poi.ts
  src/components/poi/register/poi-register.tsx
  src/components/poi/ui/poi-category.tsx
  src/components/poi/ui/poi-tag.tsx
  src/hooks/queries/useCategories.ts
  src/queries/get-categories.ts
  src/store/category.ts
  src/types/pois.ts
Labels: ✨ Feature

#127 feat: poi 조회 요청 수정
  .gitignore
  src/api/poi.ts
  src/components/common/daumAddressInput.tsx
  src/components/common/imageInput.tsx
  src/components/poi/register/poi-register.tsx
  src/components/poi/ui/poi-address.tsx
  src/components/poi/ui/poi-category.tsx
  src/components/poi/ui/poi-tag.tsx
  src/hooks/queries/useGetPOI.ts
  src/pages/search-poi-result.tsx
Labels: ✨ Feature

#129 fix: POI 상세 정보 표시 데이터 수정
  .env
  src/api/poi.ts
  src/components/main/map.tsx
  src/components/poi/poi-buttons.tsx
  src/components/poi/poi-description.tsx
  src/hooks/queries/useGetPOI.ts
  src/pages/main.tsx
  src/pages/poi.tsx
  src/pages/search-poi-result.tsx
  src/types/pois.ts
Labels: 🐞 BugFix, 🎨 Html&css, ✨ Feature

#137 feat: pwa 적용
  index.html
  package.json
  src/assets/apple-touch-icon-180x180.png
  src/assets/favicon.ico
  src/assets/maskable-icon-512x512.png
  src/assets/pwa-192x192.png
  src/assets/pwa-512x512.png
  src/assets/pwa-64x64.png
  src/components/layout/layout.tsx
  vite.config.ts
  yarn.lock
Labels: ✨ Feature

#143 Feat/128
  .env
  src/components/main/poi-list/poi-list.tsx
  src/components/my-reviews/imgItem.tsx
  src/hooks/common/logout.ts
  src/main.tsx
  src/pages/myReviews.tsx
  src/pages/mypage.tsx
  src/queries/get-poi-list.ts
  src/queries/reviewDelete.ts
  src/queries/secession.ts
Labels: ✨ Feature
